### ISSUE TITLE
The user is not redirected to the alternative browser if the Keep Last Firefox Tab on Transition is set to disabled is some circumstances

### ISSUE THREAD

**Issue by madalincm** [mozilla/legacy-browser-support#1]
### Pre-requisites:
- Keep Last Firefox Tab On  Transition policy set to disabled
- Alternative Browser Path policy set to any of the following ${ie}, ${chrome}, ${safari}
- Hosts to Open in Alternative Browser policy enabled and one website address added to the list

### Steps to reproduce:
1. Open firefox and install the legacy support extension
2. Make sure to have only one tab open
3. In the open tab enter the address of the site that is added in the list of hosts to open in the alternative browser

### Expected result:
Firefox browser is closed. The user is redirected to the page he accessed on the alternative browser set

### Actual results:
Firefox browser is closed. The alternativ browser is not open, the page is not displayed.

### Notes/Issues:
Verified in Win10x64 usin FF68.0ESR build 2.
The issue is only reproducing if the following conditions are fulfilled:
- the alternative browser is not already open. (If for example internet explorer was open and user accesses the website in list, the redirection is performed successfully)  
- Only on single tab is open in firefox and user accesses the desired website address using that tab. (If there are multiple tabs open and the user uses any of them to access the website from the list, the redirection is performed)

**Comment by mkaply** [comment]
This actually shows a bigger problem that I am debugging.

If you close Firefox, it closes the Internet Explorer instance that was opened.

**Comment by mkaply** [comment]
This is a Firefox bug.

I opened:

https://bugzilla.mozilla.org/show_bug.cgi?id=1565233

**Comment by mkaply** [comment]
I've put up a prerelease to test this:

https://github.com/mozilla/legacy-browser-support/releases/tag/v1.0

Once the fix is verified, we can get these signed.

Please make sure to uninstall the old builds first.

**Comment by madalincm** [comment]
Issue is no longer reproducing. Performed a round of regression testing and no other issues have been found.
