### ISSUE TITLE
Extension is closing wrong tab

### ISSUE THREAD

**Issue by MeikAT** [mozilla/legacy-browser-support#3]
While trying out this extension i noticed that sometimes after transitioning to Internet Explorer the wrong tab gets closed in Firefox.
After looking a bit into this extension i noticed a big difference between the chrome version and the firefox one.

In the chrome-version chrome.tabs.getCurrent is used to get the tabid which should be closed but in the firefox-version it just queries the current active tab:
Extension_Logic.js:
Line 581:                chrome.tabs.query({active: true}, function(tabs) {

Since the extension is waiting for the response from lbs_native_host.exe, when the query is executed the active tab may already changed from the extensions transition page to a tab currently in use by the user.

I'm aware that do limitations in firefox tabs.getcurrent can't be used in this case.
But there may should be a check if the tab to be closed is from the extension.

While i have no experience with extension development or javascript I tried a small adaption with already brought a better result.(but may introduce other problems, example when show_transition_screen is not 0)

Extension_Logic.js:
Line 581:      
		var exturl = browser.runtime.getURL("action.html") + "*";
                chrome.tabs.query({windowId: browser.windows.WINDOW_ID_CURRENT, url: exturl}, function(tabs) {

**Comment by mkaply** [comment]
I'm wondering if I should just be going back instead of removing the tab? Unless the tab is open by itself.

**Comment by mkaply** [comment]
I've made a change so that I know the ID of the tab that was opened and only close that tab if it has the correct URL in it. In my testing, this worked great (including opening two tabs that went to IE). I'll have something for you to test soon.

**Comment by MeikAT** [comment]
Thanks, i'm looking forward to test your change.

**Comment by mkaply** [comment]
I just uploaded 0.4 for you to try.

https://addons.mozilla.org/en-US/firefox/addon/legacy-browser-support/
