### ISSUE TITLE
(feature) Multiple route browsers

### ISSUE THREAD

**Issue by simonelbaz** [mozilla/legacy-browser-support#5]
Hi,

I wonder if it is possible to support multiple browsers and open them according an URL list in the same policy.

Thanks for your help

**Comment by mkaply** [comment]
We're looking into this feature, but have no plans right now. There are extension on AMO that support this.

**Comment by simonelbaz** [comment]
Could you please indicate me which extensions on AMO could support this ?

Thanks a lot

**Comment by mkaply** [comment]
Sure. There's one for edge that supports policy

https://addons.mozilla.org/en-US/firefox/addon/open-in-microsoft-edge-browser/

and one for Chrome that supports policy

https://addons.mozilla.org/en-US/firefox/addon/open-in-chrome-browser/

Andy Portman has written a number of these for different browsers.

https://addons.mozilla.org/en-US/firefox/user/5429276/

They require an external application to be installed (documented in the addon)
